# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-05-30 15:36
from __future__ import unicode_literals

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190529_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='boby',
            field=mdeditor.fields.MDTextField(),
        ),
    ]
